import { useState } from "react";

const NAVY="#08172e";
const SLATE="#6e90b8", SLATE2="#a8c0d8", WHITE="#f0f6ff", GOLD="#f0bc3a";

// Curated anesthesia history vignettes. Entries with month/day are pinned to
// their real anniversary; everything else rotates daily by day-of-year.
const STORIES = [
  { year:1846, month:10, day:16, title:"Ether Day", story:"On October 16, 1846, dentist William T.G. Morton publicly demonstrated ether anesthesia at Massachusetts General Hospital while surgeon John Collins Warren removed a tumor from Gilbert Abbott's neck. When the patient woke reporting no pain, Warren turned to the stunned amphitheater and declared: \"Gentlemen, this is no humbug!\"", fact:"The operating theater — the Ether Dome — still exists at MGH and you can visit it today." },
  { year:1844, month:12, day:11, title:"A Toothache Changes History", story:"Dentist Horace Wells attended a traveling laughing-gas show in Hartford and watched a volunteer gash his leg without noticing. The very next day, Wells had one of his own molars pulled while breathing nitrous oxide — and felt nothing. Modern inhalational anesthesia was born at a carnival act.", fact:"Wells's 1845 Harvard demo failed when the patient cried out — the crowd jeered \"Humbug!\" — which is why Morton's 1846 ether demo got the glory." },
  { year:1842, month:3, day:30, title:"The Quiet First", story:"On March 30, 1842, Georgia country doctor Crawford Long removed a neck tumor from James Venable under ether — four years before Ether Day. Long had noticed that friends at recreational \"ether frolics\" bruised themselves without feeling pain. He didn't publish until 1849, and lost the fame.", fact:"National Doctors' Day is celebrated on March 30 specifically to honor Long's first ether anesthetic." },
  { year:1847, month:11, day:4, title:"Chloroform at the Dinner Table", story:"On November 4, 1847, Edinburgh obstetrician James Young Simpson and two assistants sniffed chloroform samples after dinner as a self-experiment. They woke up under the dining table, delighted. Within days Simpson was using it for childbirth.", fact:"One of the first babies delivered under chloroform was affectionately nicknamed \"Anaesthesia.\"" },
  { year:1853, month:4, day:7, title:"Chloroform à la Reine", story:"On April 7, 1853, John Snow gave Queen Victoria chloroform for the birth of Prince Leopold. Religious and medical objections to labor analgesia largely evaporated overnight — if it was good enough for the Queen, it was good enough for everyone.", fact:"The same John Snow later traced London's cholera outbreak to the Broad Street pump — the first anesthesiologist was also the father of epidemiology." },
  { year:1848, month:1, day:28, title:"The First Wake-Up Call", story:"On January 28, 1848, 15-year-old Hannah Greener died under chloroform during a toenail removal — the first recorded anesthetic death, barely a year after chloroform's debut. The tragedy launched the first serious inquiries into anesthetic safety, dosing, and monitoring.", fact:"The debate it started — chloroform vs. ether safety — ran for over 50 years and shaped modern anesthesia vigilance." },
  { year:1898, month:8, day:16, title:"Spinal Anesthesia, Tested the Hard Way", story:"On August 16, 1898, August Bier performed the first planned spinal anesthetic with cocaine. Days later, he and his assistant Hildebrandt experimented on each other. Bier's dose leaked, but Hildebrandt's spinal worked — verified by hammer blows to the shins and a burning cigar to the legs, all painless.", fact:"They celebrated with wine and cigars that evening — then both spent the next week flattened by post-dural puncture headaches." },
  { year:1909, month:6, day:7, title:"Happy Birthday, Dr. Apgar", story:"Virginia Apgar, born June 7, 1909, was an anesthesiologist who transformed newborn care. In 1952 she introduced her 10-point score — legend says she first sketched it on a cafeteria napkin when a medical student asked how to assess a newborn quickly.", fact:"APGAR as a backronym (Appearance, Pulse, Grimace, Activity, Respiration) was invented a decade later — the score was simply her name." },
  { year:1846, title:"Naming the Nameless", story:"Weeks after Ether Day, physician-poet Oliver Wendell Holmes wrote to Morton suggesting a name for the new state his ether produced: \"anaesthesia,\" from the Greek for \"without sensation.\" The letter stuck, and an entire specialty inherited its name from a poet.", fact:"Holmes also suggested \"anaesthetic\" for the agent itself — nailing the specialty's entire vocabulary in one letter." },
  { year:1846, title:"The Letheon Hustle", story:"Morton tried to patent ether by disguising it — adding orange oil and aromatic dyes and calling it \"Letheon,\" after the river of forgetfulness in Greek myth. Surgeons recognized the smell of plain ether instantly, and the patent scheme collapsed within months.", fact:"Morton spent the rest of his life unsuccessfully petitioning Congress for a $100,000 reward as anesthesia's discoverer." },
  { year:1800, title:"The 44-Year-Old Hint", story:"Humphry Davy inhaled nitrous oxide, coined the name \"laughing gas,\" and wrote that it \"may probably be used with advantage during surgical operations.\" The suggestion sat ignored for 44 years while the gas headlined comedy shows and society parties.", fact:"Davy hosted nitrous evenings attended by poet Samuel Taylor Coleridge, who described the sensation as returning \"from a walk in the snow into a warm room.\"" },
  { year:1942, title:"Arrow Poison in the OR", story:"On January 23, 1942, Harold Griffith and Enid Johnson in Montreal gave curare — the Amazonian arrow poison — to a patient during an appendectomy, launching the era of muscle relaxants. Surgery no longer required deep, dangerous levels of ether.", fact:"The word curare comes from indigenous words like \"wurari\" — hunters knew for centuries that animals struck by darts died relaxed." },
  { year:1884, title:"Coca Koller", story:"Vienna ophthalmologist Karl Koller discovered that cocaine drops numbed the eye, performing the first topical local anesthesia in 1884. His friend Sigmund Freud had suggested cocaine's potential — then left on vacation and missed the discovery of a lifetime.", fact:"Colleagues nicknamed him \"Coca Koller.\" Freud reportedly regretted the missed discovery for the rest of his life." },
  { year:1962, title:"The Dissociated Discovery", story:"Ketamine was synthesized in 1962 by chemist Calvin Stevens and first given to humans in 1964 by Ed Domino. Patients seemed \"disconnected\" rather than asleep — awake-looking but profoundly anesthetized — and no existing word described it.", fact:"The term \"dissociative anesthetic\" was coined by Domino's wife Toni over the dinner table." },
  { year:1986, title:"Milk of Amnesia", story:"Propofol nearly died in development: its first formulation used a solvent (Cremophor EL) that caused anaphylaxis, and the drug was shelved. Reformulated in a soybean-oil emulsion and relaunched in 1986, the white liquid became the most used induction agent on Earth.", fact:"The nickname \"milk of amnesia\" is now so standard it appears in textbooks." },
  { year:1906, title:"The Mother of Anesthesia", story:"Alice Magaw, nurse anesthetist to the Mayo brothers, reported over 14,000 open-drop ether anesthetics without a single death attributable to anesthesia — an astonishing record for 1906. Her secret: meticulous technique and talking patients calmly to sleep.", fact:"Charles Mayo himself gave her the title \"Mother of Anesthesia.\"" },
  { year:1927, title:"The First Professor of Anesthesia", story:"Ralph Waters arrived at the University of Wisconsin in 1927 to build the world's first academic anesthesia department — residency training, morbidity conferences, research, and all. Nearly every American academic anesthesia lineage traces back to him.", fact:"His trainees proudly called themselves the \"Aqualumni\" — alumni of Waters." },
  { year:1943, title:"The Blade Everyone Knows", story:"Robert Macintosh introduced his curved laryngoscope blade in 1943 — reportedly inspired during a tonsillectomy when a Boyle-Davis gag lifted the epiglottis indirectly. He was also Oxford's first professor of anesthesia.", fact:"His Oxford chair existed only because car magnate Lord Nuffield made an anesthesia professorship a non-negotiable condition of his massive donation — over the university's objections." },
  { year:1919, title:"Tubes Born from War", story:"Repairing soldiers' shattered faces after WWI, Ivan Magill and Stanley Rowbotham needed the airway out of the surgeon's way — so they developed modern endotracheal intubation techniques with surgeon Harold Gillies, the father of plastic surgery.", fact:"Magill forceps, the Magill curve, and blind nasal intubation all came from this one collaboration." },
  { year:1926, title:"A Dog Named Airway", story:"To prove his cuffed endotracheal tube protected the lungs, Arthur Guedel anesthetized his own dog, \"Airway,\" intubated him, and submerged him in an aquarium. The dog stayed under water, ventilated through the tube, then woke and shook water over the audience.", fact:"Guedel — of Guedel's stages and the oral airway — earned the nickname \"the motorcycle anesthetist\" in WWI, supervising hospitals by bike." },
  { year:1894, title:"Two Students Invent the Anesthesia Record", story:"After witnessing anesthetic disasters as Harvard medical students, Harvey Cushing and Ernest Codman challenged each other to chart pulse and respiration during every case — creating the first anesthesia records. Cushing later added blood pressure after importing the Riva-Rocci cuff from Italy.", fact:"The \"ether charts\" were reportedly spurred by a wager over who could deliver safer anesthesia." },
  { year:1921, title:"The Forgotten Father of the Epidural", story:"Spanish military surgeon Fidel Pagés described lumbar epidural anesthesia in 1921, publishing in a Spanish journal that few abroad read. He died in a car accident two years later at 37, and the technique was independently rediscovered a decade later by Italy's Achille Dogliotti.", fact:"For years the epidural was called \"Dogliotti's method\" until Pagés's priority was recognized." },
  { year:1804, title:"Dreams in a Crystal", story:"German pharmacist Friedrich Sertürner isolated the active principle of opium around 1804 and named it morphine, after Morpheus, the god of dreams. He tested it on himself and three teenage friends — all four nearly died, which he duly reported.", fact:"Morphine was the first alkaloid ever isolated from a plant, founding modern pharmacology." },
  { year:1981, title:"A Better Way In", story:"British anesthetist Archie Brain built the first laryngeal mask airway prototypes in 1981 by hand, gluing a dental mask to a tube and testing designs on himself. The LMA went on to change airway management in operating rooms worldwide.", fact:"Brain made and tested over a hundred prototypes — many on his own airway — before commercial release in 1988." },
  { year:1974, title:"The Noise That Was the Signal", story:"Japanese engineer Takuo Aoyagi was trying to cancel out the pulsatile \"noise\" in an ear densitometer when he realized the noise itself encoded arterial oxygen saturation. That insight became pulse oximetry — arguably anesthesia's greatest safety advance.", fact:"Anesthesiologists call the pulse oximeter's beep \"the sound of safety\" — its pitch drops as saturation falls." },
  { year:1868, title:"The Sword Swallower's Contribution", story:"When physician Adolf Kussmaul wanted to prove a rigid tube could pass to the stomach in an awake human, he recruited a professional sword swallower — who calmly accepted the first esophagoscope. Laryngoscopy and airway endoscopy grew from this circus collaboration.", fact:"Early direct laryngoscopists studied sword swallowers to understand how to align the mouth, pharynx, and trachea into one axis." },
  { year:200, title:"The Lost Recipe", story:"Around 200 AD, Chinese surgeon Hua Tuo reportedly performed abdominal operations using \"mafeisan,\" an anesthetic of wine and herbal extracts. The exact recipe is lost — legend holds he burned his manuscripts in prison, and his knowledge died with him.", fact:"His name lives on: \"Hua Tuo zaishi\" (\"Hua Tuo reborn\") is still a Chinese compliment for a brilliant physician." },
  { year:1200, title:"The Soporific Sponge", story:"Medieval surgeons used the \"spongia somnifera\" — a sea sponge soaked in opium, mandrake, hemlock, and henbane, dried, then remoistened and held to the patient's nose. It sometimes worked, sometimes killed, and dosing was pure guesswork.", fact:"The recommended \"reversal agent\" was a second sponge soaked in vinegar held to the nostrils." },
  { year:1941, title:"Five Numbers Everyone Uses", story:"In 1941, the ASA introduced the physical status classification to standardize how anesthesiologists describe patient fitness. Eight decades later, \"ASA 2\" or \"ASA 4E\" remains one of the most universally understood phrases in the hospital.", fact:"The original 1941 scheme had six classes including two for emergencies — the modern \"E\" modifier came later." },
  { year:1934, title:"Thiopental and a Stubborn Myth", story:"Sodium thiopental, introduced in 1934 by Ralph Waters and John Lundy, made anesthesia induction smooth and fast for the first time. A famous claim held that thiopental killed more Pearl Harbor casualties than enemy bombs — but later reviews found scant evidence for it.", fact:"The 'Pearl Harbor anesthetic deaths' story is one of anesthesia's most repeated myths — the actual documented cases are vanishingly few." },
  { year:1934, title:"When ORs Could Explode", story:"Cyclopropane was a superb anesthetic with one catch: it was explosive. Mid-century operating rooms had conductive flooring, cotton-only scrubs, grounded equipment chains, and humidity rules — all to prevent a static spark from igniting the anesthetic itself.", fact:"Anesthesia machines still vented flammable gases away from cautery well into the 1970s in some hospitals." },
  { year:1914, title:"The Twilight Sleep Craze", story:"In the early 1900s, women traveled to Freiburg, Germany for \"Dämmerschlaf\" — twilight sleep — a morphine-scopolamine cocktail promising painless childbirth. American women formed associations demanding it, one of the first patient-led medical movements.", fact:"Mothers often remembered nothing of delivery — the amnesia, not analgesia, was doing most of the work." },
  { year:1961, title:"One Page, Sixty Years of Debate", story:"In 1961, Brian Sellick described pressing on the cricoid cartilage to occlude the esophagus during induction — in a brief Lancet paper with no controls. Cricoid pressure became worldwide dogma almost overnight, and anesthesiologists have argued about it ever since.", fact:"Sellick's original technique was tested on a handful of high-risk patients — yet it standardized rapid sequence induction globally." },
  { year:1917, title:"Boyle's Machine", story:"Henry Boyle introduced his portable nitrous-oxide/oxygen/ether apparatus in 1917, shaped by the demands of WWI casualty surgery. The design became so iconic that in much of the world, the anesthesia machine is still simply called \"the Boyle's machine.\"", fact:"Boyle reportedly demonstrated the machine's portability by wheeling it between London hospitals himself." },
  { year:1956, title:"The Nonflammable Revolution", story:"Halothane, created by ICI chemist Charles Suckling and introduced in 1956, was the first modern halogenated anesthetic: potent, smooth, and — crucially — nonflammable. Within a decade, the explosive agents and their spark-proof operating rooms became history.", fact:"Suckling designed halothane rationally from fluorine chemistry principles — one of the first \"designed\" drugs rather than a lucky find." },
  { year:1942, title:"The Word 'Oximeter'", story:"Physiologist Glenn Millikan built a lightweight ear oxygen meter for WWII fighter pilots blacking out at altitude — and coined the word \"oximeter\" for it. Aviation physiology handed anesthesiology its future standard monitor.", fact:"Millikan's oximeter clipped to the pilot's ear and drove supplemental oxygen delivery — a closed-loop system in 1942." },
  { year:1772, title:"Before It Was Funny", story:"Joseph Priestley discovered nitrous oxide in 1772 — one of several gases he isolated, including oxygen, which he called \"dephlogisticated air.\" It took Humphry Davy's self-experiments decades later to reveal the gas's giggly, pain-dulling magic.", fact:"Nitrous oxide is still in clinical use after 250 years — the oldest anesthetic drug still on the shelf." },
  { year:1840, title:"Ether Frolics", story:"Before ether was medicine, it was entertainment. At 19th-century \"ether frolics,\" students and townsfolk inhaled ether for laughs, stumbling and injuring themselves painlessly. Crawford Long watched friends bruise themselves without complaint — and connected the dots.", fact:"Traveling showmen charged 25 cents a whiff for laughing gas — anesthesia's first billing model." },
  { year:1926, title:"Balanced Anesthesia", story:"Mayo Clinic's John Lundy coined \"balanced anesthesia\" in 1926 — the idea that combining smaller doses of several agents beats a giant dose of one. It remains the core philosophy of every modern anesthetic.", fact:"Lundy also founded one of America's first blood banks at Mayo in 1935 — anesthesiologists have always moonlighted in resuscitation." },
  { year:1880, title:"The Chloroform Crime Myth", story:"Victorian newspapers loved stories of villains instantly knocking out victims with a chloroform-soaked rag. Pharmacologically, it's fiction: chloroform induction takes minutes of cooperative breathing, as any period anesthetist could attest.", fact:"The myth persists in movies today — real inhalational induction is slow enough that anesthesiologists narrate it to patients." },
];

// Anniversary match wins; otherwise rotate through the pool by day-of-year.
function pickToday() {
  const now = new Date();
  const anchored = STORIES.findIndex(s => s.month === now.getMonth() + 1 && s.day === now.getDate());
  if (anchored !== -1) return anchored;
  const doy = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 86400000);
  return (doy + now.getFullYear()) % STORIES.length;
}

export default function HistoryOfTheDay() {
  const todayIdx = pickToday();
  const [offset, setOffset] = useState(0);
  const story = STORIES[(todayIdx + offset) % STORIES.length];
  const isAnniversary = offset === 0 && story.month != null;

  return (
    <section style={{ padding:"0 24px 80px" }}>
      <div style={{ maxWidth:760, margin:"0 auto" }}>
        <div style={{ textAlign:"center", marginBottom:28 }}>
          <div style={{ display:"inline-flex", alignItems:"center", gap:8, background:`${GOLD}12`, border:`1px solid ${GOLD}40`, borderRadius:30, padding:"7px 20px", fontFamily:"'DM Mono',monospace", fontSize:12, color:GOLD, letterSpacing:1, textTransform:"uppercase", marginBottom:16 }}>
            <span style={{ width:7, height:7, borderRadius:"50%", background:GOLD, animation:"pulse 2s infinite" }}/>
            {isAnniversary ? "On This Day in Anesthesia" : "Daily Dose of History"}
          </div>
          <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(28px,5vw,44px)", fontWeight:800, letterSpacing:"-1px", color:WHITE, lineHeight:1.1 }}>
            📜 Gas <span style={{ fontStyle:"italic", color:GOLD }}>History</span>
          </h2>
        </div>

        <div key={story.title} style={{ background:`linear-gradient(135deg,${GOLD}0d,${GOLD}04)`, border:`2px solid ${GOLD}35`, borderRadius:24, padding:"34px 30px", position:"relative", overflow:"hidden", animation:"fadeUp 0.45s ease both" }}>
          <div style={{ position:"absolute", top:-24, right:-14, fontSize:110, opacity:0.05, pointerEvents:"none", lineHeight:1 }}>📜</div>
          <div style={{ display:"flex", alignItems:"baseline", gap:14, flexWrap:"wrap", marginBottom:14 }}>
            <span style={{ fontFamily:"'Playfair Display',serif", fontSize:36, fontWeight:800, color:GOLD, lineHeight:1 }}>{story.year < 1000 ? `~${story.year} AD` : story.year}</span>
            <span style={{ fontFamily:"'Playfair Display',serif", fontSize:24, fontWeight:800, color:WHITE, lineHeight:1.2 }}>{story.title}</span>
          </div>
          <p style={{ fontSize:16, color:SLATE2, lineHeight:1.8, marginBottom:20 }}>{story.story}</p>
          <div style={{ background:`${GOLD}10`, border:`1px solid ${GOLD}25`, borderRadius:12, padding:"13px 18px", fontSize:14, color:GOLD, lineHeight:1.65 }}>
            💡 {story.fact}
          </div>
          <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center", flexWrap:"wrap", gap:10, marginTop:20 }}>
            <span style={{ fontSize:12, color:SLATE, fontFamily:"monospace" }}>New story every day at midnight</span>
            <button onClick={() => setOffset(o => o + 1)}
              style={{ background:"transparent", border:`1px solid ${GOLD}40`, color:GOLD, borderRadius:9, padding:"7px 16px", cursor:"pointer", fontSize:12, fontFamily:"'DM Mono',monospace", fontWeight:700 }}>
              Another story →
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}
